### ISSUE TITLE
Remove Profile Link for Anonymous Posts (Front-End) - User Story 9

### ISSUE THREAD

**Issue by Maria-Aidarus** [CMU-17313Q/fall23-nodebb-just-relax#39]
Estimated effort: This task would be easy. This is because we would just have to update the uid of the link that will be posted on the anonymous post.

Dependencies: #12 

Acceptance criteria: The acceptance criteria of this issue would be when link for the anonymous is no longer accessible by any user.

**Comment by rama0711** [comment]
This issue is already resolved within the backend implementation choice made in sprint 1 #12
